
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides personalized style recommendations based on user preferences, including specific product suggestions.
 *
 * - getStyleRecommendation - A function that takes user preferences and returns style recommendations and product suggestions.
 * - StyleRecommendationInput - The input type for the getStyleRecommendation function.
 * - StyleRecommendationOutput - The return type for the getStyleRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { findMatchingProductsTool } from '@/ai/tools/find-products-tool';
import type { SuggestedProduct } from '@/lib/types';

const StyleRecommendationInputSchema = z.object({
  occasion: z.string().describe('L\'occasion pour laquelle la tenue est nécessaire (ex: fête, travail, décontracté).'),
  stylePreferences: z.string().describe('Description du style préféré (ex: moderne, classique, bohème, etc.).'),
  colorPreferences: z.string().describe('Couleurs préférées pour la tenue.'),
  itemPreferences: z.string().describe('Type de vêtement préféré (ex: hijab, turban, casquette, robe, etc.).'),
  faceShape: z.string().optional().describe('La forme du visage de la cliente (ex: rond, ovale, carré, long, coeur). Ce champ est crucial pour les hijabs et turbans.'),
  additionalDetails: z.string().optional().describe('Tout détail ou préférence supplémentaire.'),
});
export type StyleRecommendationInput = z.infer<typeof StyleRecommendationInputSchema>;

// Schema for suggested products (must match the tool's output)
const SuggestedProductSchemaForFlow = z.object({
  id: z.string(),
  name: z.string(),
  imageUrl: z.string(),
  price: z.number(),
  category: z.string(),
  slug: z.string(),
});

const StyleRecommendationOutputSchema = z.object({
  recommendation: z.string().describe('La recommandation de style générale générée par l\'IA, en français. Doit être amicale, experte et rassurante.'),
  reasoning: z.string().describe('Le raisonnement de l\'IA pour cette recommandation, expliquant pourquoi elle convient à la morphologie et aux goûts de la cliente, en français.'),
  suggestedProducts: z.array(SuggestedProductSchemaForFlow).optional().describe('Une liste de produits spécifiques de Dima Belle qui correspondent aux préférences. Ce champ DOIT provenir UNIQUEMENT des résultats de `findMatchingProductsTool`. Ne pas inventer de produits.'),
});
export type StyleRecommendationOutput = z.infer<typeof StyleRecommendationOutputSchema>;

export async function getStyleRecommendation(input: StyleRecommendationInput): Promise<StyleRecommendationOutput> {
  return styleRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'styleRecommendationPrompt',
  input: {schema: StyleRecommendationInputSchema},
  output: {schema: StyleRecommendationOutputSchema},
  tools: [findMatchingProductsTool],
  prompt: `Tu es une styliste experte pour Dima Belle, une marque de mode pudique et élégante, spécialisée dans les hijabs, turbans, casquettes et la morphologie du visage. Ton ton est bienveillant, professionnel et rassurant.
Une cliente recherche des conseils de style personnalisés. Ton objectif est de lui fournir une recommandation experte, d'expliquer pourquoi cette recommandation lui conviendrait, et de lui suggérer des articles de la collection Dima Belle.

Connaissances de base sur la morphologie du visage :
- Visage Rond : Cherche à ajouter de la hauteur et à allonger. Évite le volume sur les côtés. Les drapés asymétriques, les turbans hauts ou les hijabs portés avec du volume sur le dessus de la tête sont idéaux.
- Visage Carré : Cherche à adoucir les angles. Les matières fluides, les drapés doux et les bords arrondis sont parfaits. Évite les lignes trop droites et strictes.
- Visage Long/Ovale : C'est la forme la plus polyvalente. Presque tous les styles conviennent. Pour un visage long, on peut ajouter du volume sur les côtés pour équilibrer.
- Visage en Cœur/Triangle Inversé : Cherche à équilibrer un front plus large et un menton plus fin. Le volume doit être ajouté autour du cou et de la mâchoire, pas sur le dessus de la tête.

Préférences de la cliente :
- Occasion : {{{occasion}}}
- Forme du visage : {{{faceShape}}}
- Préférences de Style : {{{stylePreferences}}}
- Préférences de Couleurs : {{{colorPreferences}}}
- Type de Vêtement préféré : {{{itemPreferences}}}
- Détails Additionnels : {{{additionalDetails}}}

Instructions STRICTES :
1.  Analyse attentivement toutes les préférences de la cliente, en portant une attention particulière à la forme de son visage.
2.  **OBLIGATOIRE : Utilise l'outil 'findMatchingProductsTool'** pour rechercher des produits correspondants dans la base de données.
    *   Combine des termes pertinents de TOUTES les préférences de la cliente dans le paramètre 'keywords' de l'outil (occasion, style, couleur, forme du visage, etc.).
    *   Utilise 'itemPreferences' pour le paramètre 'category' de l'outil.
3.  **IMPORTANT : Tu NE DOIS PAS inventer de produits.** Le champ 'suggestedProducts' dans ta réponse doit contenir **UNIQUEMENT** les produits retournés par l'outil 'findMatchingProductsTool'. Si l'outil ne retourne aucun produit, le champ 'suggestedProducts' doit être un tableau vide.
4.  Formule une **recommandation de style** chaleureuse et personnalisée. Explique quel type de port (ex: "un drapé lâche sur le côté") serait le plus flatteur.
5.  Explique ton **raisonnement** en te basant sur tes connaissances en stylisme.
6.  Si l'outil a trouvé des produits, présente-les. Si l'outil n'a trouvé aucun produit, explique gentiment que tu n'as pas trouvé l'article parfait pour le moment mais donne quand même des conseils de style généraux basés sur ses préférences.
7.  Toute ta réponse doit être en français.
`,
});

const styleRecommendationFlow = ai.defineFlow(
  {
    name: 'styleRecommendationFlow',
    inputSchema: StyleRecommendationInputSchema,
    outputSchema: StyleRecommendationOutputSchema,
  },
  async (input) : Promise<StyleRecommendationOutput> => {
    const { output } = await prompt(input);
    
    if (!output) {
        throw new Error("L'IA n'a pas pu générer de recommandation.");
    }
    
    // Ensure suggestedProducts is an array, even if it's empty, if missing from AI output
    return {
        recommendation: output.recommendation || "Désolé, je n'ai pas pu générer de recommandation textuelle pour le moment.",
        reasoning: output.reasoning || "Aucun raisonnement spécifique n'a pu être fourni.",
        suggestedProducts: output.suggestedProducts || [],
    };
  }
);
